name: 'Maven CLI JDKs Action'

description: 'Github Action to execute Maven CLI commands using different JDKs'

inputs:
    commands:
        description: 'Maven commands'
        required: true
        default: 'clean package'

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.commands }}

branding:
    icon: 'package'
    color: 'blue'